"""Python parity layer for Rust-owned trading state; it never talks to Angel."""

from .domain import (
    ExitApplication,
    ExitReason,
    ExposureOrigin,
    FillApplication,
    IntentStatus,
    ManualCloseStatus,
    OrderRole,
    OrderStatus,
    ProtectionStatus,
    ReconciliationStatus,
    ReversalStatus,
    Side,
    TradeMode,
    TradeStatus,
    apply_exit_fill,
    apply_fill,
    futures_pnl_units,
    manual_broker_close_pnl,
    sl2_reversal,
    trade_pnl,
    validate_intent_transition,
    validate_manual_close_transition,
    validate_order_transition,
    validate_reversal_transition,
    validate_safety_transition,
    validate_trade_transition,
)
from .repository import TradingRepository
from .service import TradingDomainService

__all__ = [
    "ExitApplication",
    "ExitReason",
    "ExposureOrigin",
    "FillApplication",
    "IntentStatus",
    "ManualCloseStatus",
    "OrderRole",
    "OrderStatus",
    "ProtectionStatus",
    "ReconciliationStatus",
    "ReversalStatus",
    "Side",
    "TradeMode",
    "TradeStatus",
    "TradingDomainService",
    "TradingRepository",
    "apply_exit_fill",
    "apply_fill",
    "futures_pnl_units",
    "manual_broker_close_pnl",
    "sl2_reversal",
    "trade_pnl",
    "validate_intent_transition",
    "validate_manual_close_transition",
    "validate_order_transition",
    "validate_reversal_transition",
    "validate_safety_transition",
    "validate_trade_transition",
]
